# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'Big5' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Charts'

  # Pods for Big5

end
